<a href="https://colab.research.google.com/github/SilviyaDangol/From_scratch_implementations/blob/main/Multiple_variable_linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

with multiple weights for one model( multiple linear regression)
each weight gets its own gradietn, and that gradient is an average over all training examples



For each wj: sum its gradient contribution across all m examples -> divide by m -> updatte wj.

different training example-> different contributions -> sum -> divide by m-> one gradient fofr one faeature.

We do this independently for w1, w2, ... wn for n features. and then all the features and b are updated simultaneously

In [4]:
!wget https://cdn.jsdelivr.net/gh/greyhatguy007/Machine-Learning-Specialization-Coursera@main/C1%20-%20Supervised%20Machine%20Learning%20-%20Regression%20and%20Classification/week1/Optional%20Labs/lab_utils_common.py
!wget https://cdn.jsdelivr.net/gh/greyhatguy007/Machine-Learning-Specialization-Coursera@main/C1%20-%20Supervised%20Machine%20Learning%20-%20Regression%20and%20Classification/week1/Optional%20Labs/lab_utils_uni.py
!wget https://cdn.jsdelivr.net/gh/greyhatguy007/Machine-Learning-Specialization-Coursera@main/C1%20-%20Supervised%20Machine%20Learning%20-%20Regression%20and%20Classification/week1/Optional%20Labs/deeplearning.mplstyle

--2026-08-18 03:27:20--  https://cdn.jsdelivr.net/gh/greyhatguy007/Machine-Learning-Specialization-Coursera@main/C1%20-%20Supervised%20Machine%20Learning%20-%20Regression%20and%20Classification/week1/Optional%20Labs/lab_utils_common.py
Resolving cdn.jsdelivr.net (cdn.jsdelivr.net)... 104.17.208.5, 104.17.207.5, 2a04:4e42::485, ...
Connecting to cdn.jsdelivr.net (cdn.jsdelivr.net)|104.17.208.5|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/octet-stream]
Saving to: ‘lab_utils_common.py’

lab_utils_common.py     [ <=>                ]   3.18K  --.-KB/s    in 0s      

2026-08-18 03:27:21 (50.1 MB/s) - ‘lab_utils_common.py’ saved [3258]

--2026-08-18 03:27:21--  https://cdn.jsdelivr.net/gh/greyhatguy007/Machine-Learning-Specialization-Coursera@main/C1%20-%20Supervised%20Machine%20Learning%20-%20Regression%20and%20Classification/week1/Optional%20Labs/lab_utils_uni.py
Resolving cdn.jsdelivr.net (cdn.jsdelivr.net)... 151.101.1.229, 151.101.6

In [5]:
import copy, math
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('./deeplearning.mplstyle')
np.set_printoptions(precision=2)

In [6]:
# The training dataset contains three examples with four features(size, bedrooms, floors and age)

In [8]:
X_train = np.array([[2104, 5, 1, 45], [1416, 3, 2, 40], [852, 2, 1, 35]]) # 4 features in each training example
y_train = np.array([460, 232, 178]) # three training samples so 3 target values

Numpy matrix contain our training exampel. each row of the matrix represents one example.
When you have m ttraining examples and there are n features  X is a matrix with dimensions (m*n)



In [10]:
# data is stored in nmpy array/matrix

print(f"X Shape: {X_train.shape}, X Type: {type(X_train)}")
print(X_train)
print(f"y Shape: {y_train.shape}, y Type: {type(y_train)}")
print(y_train)

X Shape: (3, 4), X Type: <class 'numpy.ndarray'>
[[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]]
y Shape: (3,), y Type: <class 'numpy.ndarray'>
[460 232 178]


Parameter vector w, b
w is a vector witih n elemetns
Each element containins the parameter associated with one feature
b is a scalar parameter
w is aa 1-D NumPy vector

In [11]:
b_init = 785.1811367994083
w_init = np.array([ 0.39133535, 18.75376741, -53.36032453, -26.42131618])
print(f"w_init shape: {w_init.shape}, b_init type: {type(b_init)}")

w_init shape: (4,), b_init type: <class 'float'>


In [16]:
# Single Prediction element by element

def predict_loop(x,w,b):
  n = x.shape[0]
  p = 0
  for i in range (n): # for each feature with its own weight
    p_i = x[i] * w[i]
    p += p_i
  p = p +b
  return p

In [17]:

# single prediction vector

def predict(w,x,b):
  p = np.dot(w,x) + b
  return p

In [18]:
# get a row of the training data
x_vec = X_train[0,:]
print(f"s_vec shape {x_vec.shape}, x_vect value: {x_vec}")

# make prediction with loop
f_wb = predict_loop(x_vec, w_init, b_init)
print(f"f_wb shape {f_wb.shape}, prediction{f_wb}")

# make prediction with vector:
f_wb_v = predict(x_vec, w_init, b_init)
print(f"f_wb_v shape{f_wb_v.shape}, prediction{f_wb_v}")


s_vec shape (4,), x_vect value: [2104    5    1   45]
f_wb shape(), prediction459.9999976194083
f_wb_v shape(), prediction459.9999976194083


Cost with multiple varaibles

In [35]:
def compute_cost(x, y, w,b):
  m = x.shape[0]
  cost_sum = 0.0
  for i in range(m):
    y_pred = np.dot(x[i],w) + b
    cost = (y_pred - y[i]) ** 2
    cost_sum +=  cost
  total_cost = cost_sum/(2*m)
  return total_cost



In [36]:
# compute and display cost using pre chosen parameters
cost = compute_cost(X_train, y_train, w_init, b_init)
print(f"Cost at optimal w : {cost}")

Cost at optimal w : 1.5578904428966628e-12


Compute gradient with multiple variables


In [48]:
def compute_gradient(X, y, w, b):
  m, n = X.shape
  dj_dw = np.zeros((n,)) # Initialized as 1D array to match w_init shape
  dj_db = 0.

  for i in range(m):
    err = (np.dot(X[i], w) + b) - y[i]
    for j in range(n):
      dj_dw[j] = dj_dw[j] + err * X[i, j]
    dj_db = dj_db + err

  dj_dw = dj_dw / m
  dj_db = dj_db / m

  return dj_db, dj_dw

In [44]:
tmp_dj_db, tmp_dj_dw = compute_gradient(X_train, y_train, w_init, b_init)
print(f'dj_db at initial w,b: {tmp_dj_db}')
print(f'dj_dw at initial w,b: \n {tmp_dj_dw}')

dj_db at initial w,b: -1.6739251501955248e-06
dj_dw at initial w,b: 
 [[-2.73e-03]
 [-6.27e-06]
 [-2.22e-06]
 [-6.92e-05]]


In [45]:
def gradient_descent(X, y, w_in, b_in, cost_function, gradient_function, alpha, num_iters):
    """
    Performs batch gradient descent to learn w and b. Updates w and b by taking
    num_iters gradient steps with learning rate alpha

    Args:
      X (ndarray (m,n))   : Data, m examples with n features
      y (ndarray (m,))    : target values
      w_in (ndarray (n,)) : initial model parameters
      b_in (scalar)       : initial model parameter
      cost_function       : function to compute cost
      gradient_function   : function to compute the gradient
      alpha (float)       : Learning rate
      num_iters (int)     : number of iterations to run gradient descent

    Returns:
      w (ndarray (n,)) : Updated values of parameters
      b (scalar)       : Updated value of parameter
      """

    # An array to store cost J and w's at each iteration primarily for graphing later
    J_history = []
    w = copy.deepcopy(w_in)  #avoid modifying global w within function
    b = b_in

    for i in range(num_iters):

        # Calculate the gradient and update the parameters
        dj_db,dj_dw = gradient_function(X, y, w, b)   ##None

        # Update Parameters using w, b, alpha and gradient
        w = w - alpha * dj_dw               ##None
        b = b - alpha * dj_db               ##None

        # Save cost J at each iteration
        if i<100000:      # prevent resource exhaustion
            J_history.append( cost_function(X, y, w, b))

        # Print cost every at intervals 10 times or as many iterations if < 10
        if i% math.ceil(num_iters / 10) == 0:
            print(f"Iteration {i:4d}: Cost {J_history[-1]:8.2f}   ")

    return w, b, J_history #return final w,b and J history for graphing

In [49]:
# initialize parameters
initial_w = np.zeros_like(w_init)
initial_b = 0.0
# some gradient descent settings
iterations = 1000
alpha = 5.0e-7
# run gradient descent
w_final, b_final, J_hist = gradient_descent(X_train, y_train, initial_w, initial_b,
                                                    compute_cost, compute_gradient,
                                                    alpha, iterations)
print(f"b,w found by gradient descent: {b_final:0.2f},{w_final} ")
m,_ = X_train.shape
for i in range(m):
    print(f"prediction: {np.dot(X_train[i], w_final) + b_final:0.2f}, target value: {y_train[i]}")

Iteration    0: Cost  2529.46   
Iteration  100: Cost   695.99   
Iteration  200: Cost   694.92   
Iteration  300: Cost   693.86   
Iteration  400: Cost   692.81   
Iteration  500: Cost   691.77   
Iteration  600: Cost   690.73   
Iteration  700: Cost   689.71   
Iteration  800: Cost   688.70   
Iteration  900: Cost   687.69   
b,w found by gradient descent: -0.00,[ 0.2   0.   -0.01 -0.07] 
prediction: 426.19, target value: 460
prediction: 286.17, target value: 232
prediction: 171.47, target value: 178
